-- Ejecutar una única vez en phpMyAdmin sobre la base de datos de producción.
CREATE TABLE IF NOT EXISTS `online_checkin_links` (
  `id` int NOT NULL AUTO_INCREMENT,
  `token` varchar(128) NOT NULL,
  `status` enum('pending','completed','cancelled','expired') NOT NULL DEFAULT 'pending',
  `email` varchar(320) NOT NULL,
  `language` enum('es','en') NOT NULL DEFAULT 'es',
  `reservationNumber` varchar(100) DEFAULT NULL,
  `reservationOrigin` enum('Walk In','Booking.com','Airbnb','Expedia','Website','Phone','Email','Other') NOT NULL DEFAULT 'Website',
  `checkInDate` varchar(10) NOT NULL,
  `checkOutDate` varchar(10) NOT NULL,
  `roomNumber` varchar(10) NOT NULL,
  `roomType` varchar(100) DEFAULT NULL,
  `roomCode` varchar(20) DEFAULT NULL,
  `entranceCode` varchar(20) DEFAULT NULL,
  `numberOfRooms` int NOT NULL DEFAULT 1,
  `numberOfGuests` int NOT NULL DEFAULT 1,
  `paymentType` enum('EFECT','TARJT','TRANS','PLATF','MOVIL','TREG','DESTI','OTRO') NOT NULL DEFAULT 'TRANS',
  `amountPaid` decimal(10,2) NOT NULL DEFAULT 0.00,
  `amountPending` decimal(10,2) NOT NULL DEFAULT 0.00,
  `createdBy` int DEFAULT NULL,
  `guestId` int DEFAULT NULL,
  `expiresAt` varchar(10) NOT NULL,
  `completedAt` timestamp NULL DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `online_checkin_links_token_unique` (`token`)
);
