CREATE TABLE `cash_closings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`businessId` int NOT NULL,
	`userId` int NOT NULL,
	`date` varchar(10) NOT NULL,
	`coins010` int NOT NULL DEFAULT 0,
	`coins020` int NOT NULL DEFAULT 0,
	`coins050` int NOT NULL DEFAULT 0,
	`coins100` int NOT NULL DEFAULT 0,
	`coins200` int NOT NULL DEFAULT 0,
	`bills5` int NOT NULL DEFAULT 0,
	`bills10` int NOT NULL DEFAULT 0,
	`bills20` int NOT NULL DEFAULT 0,
	`bills50` int NOT NULL DEFAULT 0,
	`totalCash` decimal(10,2) NOT NULL DEFAULT '0',
	`totalCards` decimal(10,2) NOT NULL DEFAULT '0',
	`zReading` decimal(10,2) NOT NULL DEFAULT '0',
	`previousChange` decimal(10,2) NOT NULL DEFAULT '0',
	`prepaidBooking` decimal(10,2) NOT NULL DEFAULT '0',
	`withdrawnCash` decimal(10,2) NOT NULL DEFAULT '0',
	`withdrawnCards` decimal(10,2) NOT NULL DEFAULT '0',
	`expectedTotal` decimal(10,2) NOT NULL DEFAULT '0',
	`actualTotal` decimal(10,2) NOT NULL DEFAULT '0',
	`difference` decimal(10,2) NOT NULL DEFAULT '0',
	`changeForNextDay` decimal(10,2) NOT NULL DEFAULT '0',
	`notes` text,
	`status` enum('draft','closed') NOT NULL DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cash_closings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cash_movements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cashClosingId` int NOT NULL,
	`type` enum('in','out') NOT NULL,
	`description` varchar(255) NOT NULL,
	`amount` decimal(10,2) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `cash_movements_id` PRIMARY KEY(`id`)
);
