CREATE TABLE `online_checkin_links` (
	`id` int AUTO_INCREMENT NOT NULL,
	`token` varchar(128) NOT NULL,
	`status` enum('pending','completed','cancelled','expired') NOT NULL DEFAULT 'pending',
	`email` varchar(320) NOT NULL,
	`language` enum('es','en') NOT NULL DEFAULT 'es',
	`reservationNumber` varchar(100),
	`reservationOrigin` enum('Walk In','Booking.com','Airbnb','Expedia','Website','Phone','Email','Other') NOT NULL DEFAULT 'Website',
	`checkInDate` varchar(10) NOT NULL,
	`checkOutDate` varchar(10) NOT NULL,
	`roomNumber` varchar(10) NOT NULL,
	`roomType` varchar(100),
	`roomCode` varchar(20),
	`entranceCode` varchar(20),
	`numberOfRooms` int NOT NULL DEFAULT 1,
	`numberOfGuests` int NOT NULL DEFAULT 1,
	`paymentType` enum('EFECT','TARJT','TRANS','PLATF','MOVIL','TREG','DESTI','OTRO') NOT NULL DEFAULT 'TRANS',
	`amountPaid` decimal(10,2) NOT NULL DEFAULT '0',
	`amountPending` decimal(10,2) NOT NULL DEFAULT '0',
	`createdBy` int,
	`guestId` int,
	`expiresAt` varchar(10) NOT NULL,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `online_checkin_links_id` PRIMARY KEY(`id`),
	CONSTRAINT `online_checkin_links_token_unique` UNIQUE(`token`)
);
