CREATE TABLE `chef_sandwich_orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderDate` varchar(10) NOT NULL,
	`burguerBoxes` int NOT NULL DEFAULT 0,
	`burguerUnits` int NOT NULL DEFAULT 0,
	`mojoBoxes` int NOT NULL DEFAULT 0,
	`mojoUnits` int NOT NULL DEFAULT 0,
	`serranitoBoxes` int NOT NULL DEFAULT 0,
	`serranitoUnits` int NOT NULL DEFAULT 0,
	`lomoWBoxes` int NOT NULL DEFAULT 0,
	`lomoWUnits` int NOT NULL DEFAULT 0,
	`frankfurtBoxes` int NOT NULL DEFAULT 0,
	`frankfurtUnits` int NOT NULL DEFAULT 0,
	`tortillaBoxes` int NOT NULL DEFAULT 0,
	`tortillaUnits` int NOT NULL DEFAULT 0,
	`empanadoBoxes` int NOT NULL DEFAULT 0,
	`empanadoUnits` int NOT NULL DEFAULT 0,
	`bbqBoxes` int NOT NULL DEFAULT 0,
	`bbqUnits` int NOT NULL DEFAULT 0,
	`polloBaconBoxes` int NOT NULL DEFAULT 0,
	`polloBaconUnits` int NOT NULL DEFAULT 0,
	`carbonaraBoxes` int NOT NULL DEFAULT 0,
	`carbonaraUnits` int NOT NULL DEFAULT 0,
	`yorkBoxes` int NOT NULL DEFAULT 0,
	`yorkUnits` int NOT NULL DEFAULT 0,
	`serranoBoxes` int NOT NULL DEFAULT 0,
	`serranoUnits` int NOT NULL DEFAULT 0,
	`piripiBoxes` int NOT NULL DEFAULT 0,
	`piripiUnits` int NOT NULL DEFAULT 0,
	`tostaBarbacoa` int NOT NULL DEFAULT 0,
	`tostaCarbonara` int NOT NULL DEFAULT 0,
	`tostaPolloBoxes` int NOT NULL DEFAULT 0,
	`tostaPolloUnits` int NOT NULL DEFAULT 0,
	`tostaRuloCabra` int NOT NULL DEFAULT 0,
	`tosta3Quesos` int NOT NULL DEFAULT 0,
	`tostaYork` int NOT NULL DEFAULT 0,
	`bocapizzaYork` int NOT NULL DEFAULT 0,
	`bocapizzaBacon` int NOT NULL DEFAULT 0,
	`bocapizzaBBQ` int NOT NULL DEFAULT 0,
	`bocapizza4Q` int NOT NULL DEFAULT 0,
	`bocapizzaAtun` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `chef_sandwich_orders_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `inventory_products` (
	`id` int AUTO_INCREMENT NOT NULL,
	`handle` varchar(100),
	`ref` varchar(50),
	`name` varchar(255) NOT NULL,
	`category` varchar(100),
	`cost` decimal(10,2) NOT NULL DEFAULT '0',
	`price` decimal(10,2) NOT NULL DEFAULT '0',
	`inStock` decimal(10,3) NOT NULL DEFAULT '0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `inventory_products_id` PRIMARY KEY(`id`),
	CONSTRAINT `inventory_products_handle_unique` UNIQUE(`handle`)
);
